flanguage: node_js
node_js:
- '7'
dist: trusty
sudo: required
before_script:
- npm install
- npm install -g gulp-cli
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
- npm run test
git:
  depth: false
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8 CC=gcc-4.8
branches:
  except:
  - /^v?\d+\.\d+\.\d+$/
addons:
  - apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  - code_climate
  - chrome: stable
before_deploy:
- npm run release
- npm run gh-pages
- sh ./scripts/build_commit.sh && npm version patch && PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- echo '${PACKAGE_VERSION}'
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    tag: next
    name: ${PACKAGE_VERSION}
    file:
      - "./dist/cmd-resume.js"
      - "./dist/cmd-resume.min.js"
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: ./tmp
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: cmd-resume.bbody.io
    repo: bbody/CMD-Resume
    tag: next
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "bbody.project@gmail.com"
    api_key: $NPMJS_TOKEN
    tag: next
    on:
      branch: master
      tags: true
  - provider: script
    script: sh ./scripts/push.sh
    on:
      branch: master
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
